# get the base node image
FROM node:16.14.0-alpine as builder

# set the working dir for container
WORKDIR /frontend

# copy the json file first
COPY . .

# install npm dependencies
RUN npm install

# copy other project files


# build the folder
RUN npm run build

# Handle Nginx
FROM nginx
COPY --from=builder /frontend/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf